import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { TaskStoreProvider } from "@/providers/task-store-provider";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";



const poppins = Poppins({
  variable: "--font-poppins",
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}  antialiased`}
      >
        <TaskStoreProvider>
          <div className="flex min-h-screen">
            <Header />
            <Sidebar />

            <main className="flex-1">{children}</main>

          </div>
        </TaskStoreProvider>
      </body>
    </html>
  );
}
